### ISSUE TITLE
http2: Transport received Server's graceful shutdown GOAWAY

### ISSUE THREAD

**Issue by phramz** [uploadcare/uploadcare-go#11]
### Describe the bug

Not always but multiple times per day I face the following error when deleting images:

```
Delete "https://api.uploadcare.com/files/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/storage/": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error"
```

### Expected behavior

Client would retry automatically.

### Code / screenshots

```
  import (
    "github.com/uploadcare/uploadcare-go/file"
    "github.com/uploadcare/uploadcare-go/upload"
  )

  client, _ := ucare.NewClient(ucare.APICreds{
	SecretKey: secretKey,
	PublicKey: publicKey,
  }, &ucare.Config{
	SignBasedAuthentication: true,
	APIVersion:              ucare.APIv06,
  })


  files := file.NewService(client)
  _, err := files.Delete(ctx, "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx") // error
```

### Environment

 - Library version: `github.com/uploadcare/uploadcare-go v1.2.2`
 - Language/framework version: `go version go1.17`
 - OS version: `alpine:latest`

**Comment by optlsnd** [comment]
Hi @phramz, Would you be able to share a few exact UUIDs along with timestamps of the delete requests so that we can check our logs to see what went wrong?

**Comment by phramz** [comment]
@optlsnd i sent you an invite to a private repo where you can find the latest error logs UUIDs and timestamps

**Comment by optlsnd** [comment]
@phramz in our logs, we can see those files have been successfully deleted and our server never responded with errors.

GOAWAY is an HTTP2-specific thing, and it would be helpful to find out what exactly your client receives from our server. Would you be able to temporarily [force your client to use HTTP/1.1](https://github.com/grafana/k6/issues/936#issuecomment-470505275) instead of 2.0 to do so and show us the result?

Also, the regular golang HTTP client doesn't retry DELETE requests according to the [spec](https://pkg.go.dev/net/http)

> Transport only retries a request upon encountering a network error if the request is idempotent and either has no body or has its Request.GetBody defined. HTTP requests are considered idempotent if they have HTTP methods GET, HEAD, OPTIONS, or TRACE; or if their Header map contains an "Idempotency-Key" or "X-Idempotency-Key" entry. If the idempotency key value is a zero-length slice, the request is treated as idempotent but the header is not sent on the wire.

so you might need to implement a custom retry logic on your end.

**Comment by phramz** [comment]
@optlsnd thanks for looking into it. I will downgrade to HTTP1.1 and see if it work for me. Since its a bit tricky to reliably reproduce this issue Im going to just give it a try and keep you posted about any news regarding this.

**Comment by phramz** [comment]
Enforcing HTTP1.1 seems to solve the issue. The error didn't appear since then. Just for the record ...here's the snipped:

```
client, err := ucare.NewClient(ucare.APICreds{
	SecretKey: secretKey,
	PublicKey: publicKey,
}, &ucare.Config{
	SignBasedAuthentication: true,
	APIVersion:              ucare.APIv06,
	HTTPClient: func() *http.Client {
		httpDefaultClient := *http.DefaultClient
		httpDefaultClient.Transport = &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			DialContext: (&net.Dialer{
				Timeout:   30 * time.Second,
				KeepAlive: 30 * time.Second,
			}).DialContext,
			ForceAttemptHTTP2:     false,
			MaxIdleConns:          100,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
			TLSNextProto:          make(map[string]func(authority string, c *tls.Conn) http.RoundTripper),
		}
		
		return &httpDefaultClient
	}(),
})
```

Thanks @optlsnd for your support! +1

... closing
