### ISSUE TITLE
Cannot rename when upload from url

### ISSUE THREAD

**Issue by hilmanski** [uploadcare/uploadcare-go#22]
### Describe the bug

I can't give a new name when uploading via url

### Expected behavior

I can have a new custom name

### Code / screenshots

```
 filename := newName + ".png"
 params := upload.FromURLParams{
		URL: url,
		ToStore: &storeValue,
		Name: &filename,
	}
```

it upload to Uplaodcare, but with original name, not the one I customized at "Name" parameter

### Environment

 - Library version: newest
 - Language/framework version: Golang
 - OS version:

**Comment by rsedykh** [comment]
Hi @hilmanski. We're looking into this issue. Sorry that it takes so long, we were out of Golang expertise for a while. :-)

**Comment by rsedykh** [comment]
@hilmanski check the latest release https://github.com/uploadcare/uploadcare-go/releases/tag/v1.2.5
